import { readFileSync } from 'node:fs';
import path from 'node:path';

import { GENERATED_DIR, ROOT, parseArgs } from './lib.mjs';

/**
 * Emit the unit -> glb lookup that the visual registry consumes.
 *
 * Written as a .ts module of `require()` calls because Metro resolves asset
 * requires statically; a runtime path string would not be bundled.
 */
function main() {
  const args = parseArgs();

  // --stub writes the empty version. The populated file requires .glb binaries
  // that are gitignored (they are derived from the user's own map), so a clone
  // without the assets uses the stub and every unit falls back to a primitive.
  const models = args.stub
    ? { converted: [] }
    : JSON.parse(readFileSync(path.join(GENERATED_DIR, 'models.raw.json'), 'utf8'));

  // unitId -> asset name, from every unit that shares a converted model.
  const byUnit = new Map();
  const assets = new Set();
  for (const entry of models.converted) {
    assets.add(entry.asset);
    for (const unitId of entry.unitIds) byUnit.set(unitId, entry.asset);
  }

  const assetNames = [...assets].sort();
  const lines = [
    '// Generated by tools/w3x/build-visuals.mjs — do not edit.',
    '//',
    '// The .glb files live in assets/models/generated/ and are gitignored: they are',
    '// derived from the user\'s own copy of the source map. Run',
    '//   node tools/w3x/mdx2glb.mjs && node tools/w3x/build-visuals.mjs',
    '// to regenerate them.',
    '',
    'export const GENERATED_MODELS: Record<string, number> = {',
    ...assetNames.map((name) => `  '${name}': require('@/assets/models/generated/${name}.glb'),`),
    '};',
    '',
    '/** Unit id -> generated model asset name. */',
    'export const UNIT_MODEL: Record<string, string> = {',
    ...[...byUnit.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([unitId, asset]) => `  '${unitId}': '${asset}',`),
    '};',
    '',
  ];

  const outFile = path.join(ROOT, 'src/game/render/visuals/generated.ts');
  const { writeFileSync, mkdirSync } = require('node:fs');
  mkdirSync(path.dirname(outFile), { recursive: true });
  writeFileSync(outFile, lines.join('\n'));

  console.log(`assets: ${assetNames.length}, units mapped: ${byUnit.size}`);
  console.log(`wrote ${path.relative(ROOT, outFile)}`);
}

const { createRequire } = await import('node:module');
const require = createRequire(import.meta.url);
main();
