// Generated by tools/w3x/build-visuals.mjs — do not edit.
//
// The .glb files live in assets/models/generated/ and are gitignored: they are
// derived from the user's own copy of the source map. Run
//   node tools/w3x/mdx2glb.mjs && node tools/w3x/build-visuals.mjs
// to regenerate them.

export const GENERATED_MODELS: Record<string, number> = {
};

/** Unit id -> generated model asset name. */
export const UNIT_MODEL: Record<string, string> = {
};
